### Crear un nuevo Paquete
POST http://localhost:6000/api/paquetes HTTP/1.1
Content-Type: application/json

{
    "Destino": "San Andres",
    "Actividad": "Buceo",
    "numeroPersonas": 7,
    "categoria": Meedia,
    "precio": "1500000",
    "transporte": "Bus",
    "Comida": "Desayuno incluido",
}
###

### Obtener todos los Paquetes
GET http://localhost:6000/api/Paquetes HTTP/1.1
###

### Obtener un Paquetes específico por ID
GET http://localhost:6000/api/paquetes/67282a47404d29c3a729b47a HTTP/1.1
###

### Actualizar un paquete específico por ID
PUT http://localhost:6000/api/paquetes/672319b7761480d7fa6b08d0 HTTP/1.1
Content-Type: application/json

{
     "Destino": "Santa Marta",
    "Actividad": "Acuario",
    "numeroPersonas": 8,
    "categoria": Meedia,
    "precio": "1600000",
    "transporte": "Bus",
    "Comida": "Desayuno y almuerzo incluido",
}
###

### Eliminar un paquete específico por ID
DELETE http://localhost:6000/api/paquetes/6723256cd3ec2f85890b0357 HTTP/1.1
